domain: curtispoe.org
url: https://curtispoe.org/
tagmap_file: tagmap.json
tagmap:
  ai: AI
  business: Business
  corinna: Corinna
  databases: Databases
  expat: Moving Abroad
  family: Family
  math: Math
  oop: OOP
  perl: Perl
  personal: Personal
  politics: Politics
  programming: Software
  science: Science
  space: Space
  writing: Writing
max_image_size_bytes: 300000 # 300KB limit for uploaded images (linting + upload validation)
